Document: ipc
Title: Debian ipc Manual
Author: <insert document author here>
Abstract: This manual describes what ipc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ipc/ipc.sgml.gz

Format: postscript
Files: /usr/share/doc/ipc/ipc.ps.gz

Format: text
Files: /usr/share/doc/ipc/ipc.text.gz

Format: HTML
Index: /usr/share/doc/ipc/html/index.html
Files: /usr/share/doc/ipc/html/*.html

  
